-- DDL for Demo Insurance Application

-- Drop tables if they exist (in reverse order of dependencies)
DROP TABLE TRANSACTIONS;
DROP TABLE CLAIMS;
DROP TABLE POLICIES;
DROP TABLE CUSTOMERS;
DROP TABLE ACCOUNTS;
DROP TABLE AGENTS;

-- Agents Table
CREATE TABLE AGENTS (
    AGENT_ID BIGINT NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    REGION VARCHAR(50),
    STATED_COMMISSION DECIMAL(5,2)
);

-- Accounts Table
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID BIGINT NOT NULL PRIMARY KEY,
    ACCOUNT_NAME VARCHAR(100),
    AGENT_ID BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    STATUS VARCHAR(20),
    FOREIGN KEY (AGENT_ID) REFERENCES AGENTS(AGENT_ID) ON DELETE SET NULL
);

-- Customers Table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID BIGINT NOT NULL PRIMARY KEY,
    ACCOUNT_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    ZIP_CODE VARCHAR(10),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID) ON DELETE CASCADE
);

-- Policies Table
CREATE TABLE POLICIES (
    POLICY_ID BIGINT NOT NULL PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    AGENT_ID BIGINT,
    POLICY_TYPE VARCHAR(20), -- Life, Auto, Home, etc.
    START_DATE DATE,
    END_DATE DATE,
    PREMIUM_AMOUNT DECIMAL(10,2),
    COVERAGE_AMOUNT DECIMAL(15,2),
    STATUS VARCHAR(20),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE,
    FOREIGN KEY (AGENT_ID) REFERENCES AGENTS(AGENT_ID) ON DELETE SET NULL
);

-- Claims Table
CREATE TABLE CLAIMS (
    CLAIM_ID BIGINT NOT NULL PRIMARY KEY,
    POLICY_ID BIGINT NOT NULL,
    CLAIM_DATE DATE,
    INCIDENT_DATE DATE,
    CLAIM_AMOUNT DECIMAL(15,2),
    PAID_AMOUNT DECIMAL(15,2),
    STATUS VARCHAR(20), -- Open, Closed, Denied, Pending
    DESCRIPTION CLOB,
    FOREIGN KEY (POLICY_ID) REFERENCES POLICIES(POLICY_ID) ON DELETE CASCADE
);

-- Transactions Table
CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID BIGINT NOT NULL PRIMARY KEY,
    ACCOUNT_ID BIGINT NOT NULL,
    POLICY_ID BIGINT,
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    AMOUNT DECIMAL(15,2),
    TRANSACTION_TYPE VARCHAR(20), -- Premium Payment, Claim Payout, Refund
    DESCRIPTION VARCHAR(255),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID) ON DELETE CASCADE,
    FOREIGN KEY (POLICY_ID) REFERENCES POLICIES(POLICY_ID) ON DELETE SET NULL
);
